"""update student-v1

Revision ID: cc3c8d269070
Revises: c6a8b21733d3
Create Date: 2024-09-12 14:40:20.323596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc3c8d269070'
down_revision: Union[str, None] = 'c6a8b21733d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('students', 'degree',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'date_of_registration',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('students', 'graduation_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('students', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'contact_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'contact_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('students', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'graduation_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('students', 'date_of_registration',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('students', 'degree',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('students', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
